version: "3.9"

services:
  db:
    image: postgres:15
    container_name: tpespecial_db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=Admin20250915
      - POSTGRES_DB=tpespecialweb
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d tpespecialweb"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata_dev:/var/lib/postgresql/data
      - ./db/schema:/docker-entrypoint-initdb.d/

  app:
    image: cosmtrek/air
    container_name: tpespecial_app
    working_dir: /app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 2s
      retries: 15
    environment:
      - DB_URL=postgres://admin:Admin20250915@db:5432/tpespecialweb?sslmode=disable
    volumes:
      - .:/app
    command: ["air", "-c", ".air.toml"]
    restart: unless-stopped

volumes:
  pgdata_dev: